name: Validate PR

on: 
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.17.0'
    - name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - run: yarn
    - run: yarn build
