name: Validate PR for Bahmni Form Controls

on:
  pull_request:
    branches: 
      - master
      - 'fix-node'
    types: [ opened, synchronize, reopened ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Node JS v14.2.0
        uses: actions/setup-node@v4
        with:
          node-version: 14.2.0
          registry-url: 'https://registry.npmjs.org'
          architecture: 'x64'
      - run: yarn cache clean
      - name: Install dependencies
        run: brew install automake autoconf libtool dpkg pkgconfig nasm libpng
      - name: yarn Install
        run: yarn
      - name: yarn test
        run: yarn test